name: DeployGate

on:
  deployment:
  push:
    branches:
      - master

jobs:
  deploygate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        env:
          SLACK_COMMON_WEBHOOK_URI: ${{secrets.SLACK_COMMON_WEBHOOK_URI}}
          SLACK_WEBHOOK_DEV_CHANNEL: ${{secrets.SLACK_WEBHOOK_DEV_CHANNEL}}
        run: ./gradlew assembleDebug

      - name: Distribute App
        run: |
          curl \
            -F "token=${{secrets.DEPLOYGATE_TOKEN}}" \
            -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
            -F "distribution_name=$GITHUB_REF" \
            https://deploygate.com/api/users/${{secrets.DEPLOYGATE_USER_NAME}}/apps
