name: pull request workflow

on:
  pull_request:
  repository_dispatch:
    types: [trigger-pull-req]

jobs:
  firebase_test_lab:
    needs: deploygate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

      - name: Build with Gradle
          env:
            SLACK_COMMON_WEBHOOK_URI: ${{secrets.SLACK_COMMON_WEBHOOK_URI}}
            SLACK_WEBHOOK_DEV_CHANNEL: ${{secrets.SLACK_WEBHOOK_DEV_CHANNEL}}
          run: ./gradlew assembleDebug

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - run: gcloud info

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: |
          gcloud firebase test android run \
            --type robo \
            --app app-debug/app-debug.apk \
            --device model=Nexus6,version=21,locale=ja,orientation=portrait  \
            --device model=sailfish,version=25,locale=ja,orientation=portrait \
            --device model=zeroflte,version=22,locale=ja,orientation=portrait \
            --timeout 90s

