name: Run inspection on push

on: pull_request

jobs:
  inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run Ktlint
        run: ./gradlew ktlint

      - name: run danger-kotlin
        uses: danger/kotlin@0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          